version: "1.0"
services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Presentations/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTP_PORT=8081
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
      - mongodb
      - redis
        
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest" 
    environment:
      SA_PASSWORD: "Password123*"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
       
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
      
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/data